-- 1. WAQTD NAME OF THE EMPLOYEE AND HIS MANAGERS NAME IF EMPLOYEE IS WORKING AS CLERK
SELECT E1.FIRST_NAME ||' '|| E1.LAST_NAME AS "EMPLOYEE NAME",E1.JOB_ID, E2.FIRST_NAME, E2.LAST_NAME
FROM EMPLOYEES E1, EMPLOYEES E2
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID AND E1.JOB_ID = 'PU_CLERK';

-- 2. WAQTD NAME OF THE EMPLOYEE AND MANAGER'S DESIGNATION IF MANAGER WORKS IN DEPT 10 OR 20.

SELECT E1.FIRST_NAME || ' ' || E1.LAST_NAME AS " EMPLOYEE NAME", E2.FIRST_NAME || ' '|| E2.LAST_NAME AS "MANAGERS  NAME", E2.JOB_ID 
FROM EMPLOYEES E1, EMPLOYEES E2
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID AND E2.DEPARTMENT_ID IN (50,80);


