SELECT * FROM EMPLOYEES;
SET LINES 100 PAGES 100;

DESCRIBE EMPLOYEES;
-- LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL

SELECT * FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

SELECT * FROM EMPLOYEES 
WHERE COMMISI

SELECT * FROM JOBS;

SELECT * FROM EMPLOYEES WHERE JOB_ID NOT IN 'FI_ACCOUNT';





SELECT FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE 'H%' OR FIRST_NAME LIKE 'T%';
--SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE IN( LIKE 'H%', LIKE 'T%');

SELECT 



