-- 1.NAME OF THE EMPLOYEE AND HIS LOCATION OF ALL THE EMPLOYEES .

SELECT ENAME,LOC
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO;

-- 2.WAQTD DNAME AND SALARY FOR ALL THE EMPLOYEE WORKING IN ACCOUNTING.

SELECT ENAME,DNAME,SAL
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND DNAME IN 'ACCOUNTING';

-- 3.WAQTD DNAME AND ANNUAL SALARY FOR ALL EMPLOYEES WHOS SALARY IS MORE THAN 2340

SELECT ENAME,DNAME,SAL*12 AS ANNUALSAL
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND SAL>2340;
-- 4.WAQTD ENAME AND DNAME FOR EMPLOYEES HAVING CAHARACTER 'A' IN THEIR DNAME

SELECT ENAME,DNAME
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND DNAME LIKE '%A%';

-- 5.WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES WORKING AS SALESMAN

 SELECT ENAME,DNAME
 FROM EMP,DEPT
 WHERE EMP.DEPTNO=DEPT.DEPTNO AND JOB='SALESMAN';

-- 6.WAQTD DNAME AND MGR NO FOR EMPLOYEES REPORTING TO 7839

SELECT DNAME,MGR,ENAME
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND MGR IN (SELECT EMPNO
FROM EMP
WHERE EMPNO=7839);



-- 7.WADTD DNAME AND JOB FOR ALL THE EMPLOYEES WHOS JOB AND DNAME STARTS WITH CHARACTER 'S'
SELECT DNAME, JOB, ENAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND JOB LIKE 'S%' AND DNAME LIKE 'S%';


-- 8.WAQTD DNAME AND HIREDATE FOR EMPLOYEES HIRED AFTER 83 INTO ACCOUNTING OR RESEARCH DEPT
SELECT DNAME, HIREDATE, ENAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE HIREDATE > '31-DEC-83' AND DNAME IN ('ACCOUNTING', 'RESEARCH');


-- 9.WAQTD ENAME AND DNAME OF THE EMPLOYEES WHO ARE GETTING COMM IN DEPT 10 OR 30
SELECT ENAME, DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND COMM IS NOT NULL AND EMP.DEPTNO IN (10, 20);

--10.WAQTD DNAME AND EMPNO FOR ALL THE EMPLOYEES WHO'S EMPNO ARE (7839,7902) AND ARE WORKING IN LOC NEW YORK.

SELECT DNAME, EMPNO, ENAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMPNO IN (7839,7902) AND LOC IN 'NEW YORK';
