INSERT INTO table_name values (val`, val2, .... ,valn);
DESCRIBE STUDENT;
CREATE TABLE STD (rollno NUMBER(4) PRIMARY KEY,
NAME VARCHAR(15) NOT NULL,
STREAM VARCHAR(10) NOT NULL,
GLR NUMBER(4), 
DOJ DATE,
FEE NUMBER(8,2) CHECK(FEE>0),
PENDING NUMBER(8,2),
YEAR NUMBER(1) CHECK(YEAR>0 AND YEAR<11));

DESCRIBE STD;

INSERT INTO STD (rollno, NAME, STREAM, GLR, DOJ, FEE, PENDING, YEAR) VALUES ()
INSERT INTO STD VALUES (5454,'DINGA','EXT',8267,'26-May-18',49860, NULL, 4);

SELECT * FROM STD;
INSERT INTO STD VALUES  (&rollno, &NAME, &STREAM, &GLR, &DOJ, &FEE, &PENDING, &YEAR);
INSERT INTO STD VALUES (&rollno, &NAME, &STREAM, &GLR, &DOJ, &FEE, &PENDING, &YEAR);

INSERT INTO STD VALUES(&rollno, &NAME, &STREAM, &GLR, &DOJ, &FEE, &PENDING, &YEAR);
INSERT INTO STD VALUES (1432, SHEELA, CIVIL, 6244 , 01-Jun-21, 50650, 12650 ,2)
INSERT INTO STD VALUES( 7864 MAALA EEE 7733 03-Jul-20 55760 16760 3 
