-- 1.WAQTD SMITHS REPORTING MANAGER'S NAME
							SELECT LAST_NAME ||' '|| LAST_NAME AS "Employee Name"
							FROM EMPLOYEES
							WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
							                FROM EMPLOYEES
							                WHERE LAST_NAME = 'Smith');

-- 2.WAQTD ADAMS MANAGER'S MANAGER NAME
SELECT LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
		FROM EMPLOYEES
		WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
                		FROM EMPLOYEES
				WHERE LAST_NAME IN 'ADAMS'));

-- 3.WAQTD DNAME OF JONES MANAGER
SELECT DNAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                 FROM EMPLOYEES
                 WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
				 FROM EMPLOYEES
				 WHERE LAST_NAME IN 'JONES'));

-- 4.WAQTD MILLER'S MANAGER'S SALARY
SELECT SAL
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
                FROM EMPLOYEES
                WHERE LAST_NAME = 'MILLER');

-- 5.WAQTD LOCATION_IDOF SMITH'S MANAGER'S MANAGER.
SELECT LOCATION_ID
FROM DEPARTMENTS                                                                                                                      
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
		FROM EMPLOYEES
		WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
                		FROM EMPLOYEES
				WHERE LAST_NAME IN 'SMITH'));


-- 6.WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE
SELECT LAST_NAME
FROM EMPLOYEES
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID
	      FROM EMPLOYEES
	      WHERE LAST_NAME IN 'Smith'); 
		  SELECT * FROM EMPLOYEES WHERE LAST_NAME= 'Smith';

-- 7.WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING
SELECT COUNT(*)
FROM EMPLOYEES
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID
	      FROM EMPLOYEES
	      WHERE LAST_NAME IN 'KING');

-- 8.WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES
SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID
	      FROM EMPLOYEES
	      WHERE LAST_NAME IN 'JONES');

-- 9.WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER
SELECT LAST_NAME
FROM EMPLOYEES
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID
		FROM EMPLOYEES
		WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
                		FROM EMPLOYEES
				WHERE LAST_NAME IN 'BLAKE'));


-- 10.WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER
SELECT COUNT(*)
FROM EMPLOYEES
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID
		FROM EMPLOYEES
		WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
                		FROM EMPLOYEES
				WHERE LAST_NAME IN 'FORD'));