SELECT FIRST_NAME || LAST_NAME AS "EMPLOYEE NAME"  FROM EMPLOYEES WHERE  DEPARTMENT_ID IS NULL;
SELECT * FROM DEPARTMENTS;
SELECT FIRST_NAME || LAST_NAME AS "EMPLOYEE NAME" , DEPARTMENT_ID FROM EMPLOYEES WHERE  DEPARTMENT_ID IS NULL;


-- SELECT FIRST_NAME || LAST_NAME AS "EMPLOYEE NAME" 
-- FROM ;


SELECT * FROM EMPLOYEES WHERE IN SALARY < (SELECT * FROM EMPLOYEES WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES));
DESCRIBE EMPLOYEES;




